name: Deploy to Streamlit Cloud

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create Streamlit secrets
      run: |
        mkdir -p ~/.streamlit
        echo "${{ secrets.STREAMLIT_CREDENTIALS }}" > ~/.streamlit/credentials.toml
        echo "[server]" > ~/.streamlit/config.toml
        echo "headless = true" >> ~/.streamlit/config.toml
        echo "enableCORS = false" >> ~/.streamlit/config.toml
        echo "enableXsrfProtection = false" >> ~/.streamlit/config.toml
        echo "scriptPath = \"streamlit_app.py\"" >> ~/.streamlit/config.toml
    
    - name: Deploy to Streamlit Cloud
      env:
        STREAMLIT_API_KEY: ${{ secrets.STREAMLIT_API_KEY }}
      run: |
        streamlit run streamlit_app.py &
        sleep 10  # Give Streamlit time to start
