name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-modal:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install modal
    
    - name: Create Modal token file
      run: |
        echo "[adammoore]" > ~/.modal.toml
        echo "token_id = \"${{ secrets.MODAL_TOKEN_ID }}\"" >> ~/.modal.toml
        echo "token_secret = \"${{ secrets.MODAL_TOKEN_SECRET }}\"" >> ~/.modal.toml
        echo "active = true" >> ~/.modal.toml
        cat ~/.modal.toml
    
    - name: Deploy to Modal
      run: |
        modal deploy serve_streamlit.py

  deploy-streamlit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install streamlit
    
    - name: Deploy to Streamlit Cloud
      uses: streamlit/streamlit-deploy@v1
      with:
        app-name: orcid-affiliation-dashboard
        streamlit-credentials: ${{ secrets.STREAMLIT_CREDENTIALS }}
